---
image: amd64/debian:stable-slim

cache:
  key: cache-folder
  paths:
    - cache/

before_script:
  - mkdir -p cache/deb
  - apt-get update -yqq
  - apt-get -o dir::cache::archives='cache/deb' install -yqq perl make binutils findutils tar gzip wget file git

pages:
  stage: build
  variables:
    KEEP_PKG: 20
  script:
    - mkdir -p public/download
    - $(wget --no-check-certificate ${CI_PAGES_URL}/download.tar.gz -O download.tar.gz || exit 0)
    - 'file download.tar.gz | grep "gzip compressed data" && { tar -xzf download.tar.gz public/download/ || echo "untar error" ; }'
    - make webpages
    - tar -czf public/download.tar.gz public/download/
  artifacts:
    paths:
      - public
    expire_in: 3 day
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
