#!/bin/bash
#
# 2026/07/24 Gabriel Moreau <Gabriel.Moreau@univ-grenoble-alpes.fr>

set -euo pipefail

# Clean at end of script in all case
trap 'rm -rf "${tmp_folder:-}"' EXIT QUIT

export PATH=/bin:/sbin:/usr/bin:/usr/sbin
export LANG=C

# Check build commands
for cmd in ar tar gzip pod2man mktemp du cut install
do
  command -v "$cmd" >/dev/null || {
    echo "error: $cmd missing"
    exit 1
  }
done

# Temporary folder
tmp_folder=$(mktemp --directory /tmp/sat-XXXXXX)
[ -n "${tmp_folder}" ] && [ -d "${tmp_folder}" ] || exit 1

# Set Name and Version
PKG_NAME=sat
CODE_VERSION=$(./get-version)
PKG_VERSION=1
[ -n "${CODE_VERSION}" ] || {
  echo "error: Empty version"
  exit 1
}

# Transform version
for f in sat satq satrm sat-run *.pod
do
  sed "s/@VERSION@/${CODE_VERSION}/g;" "${f}" > "${tmp_folder}/${f}"
done

# Install files
install -Dm 0755 -t "${tmp_folder}"/usr/bin/                "${tmp_folder}"/sat "${tmp_folder}"/satq "${tmp_folder}"/satrm
install -Dm 0755 -t "${tmp_folder}"/usr/libexec/sat/        "${tmp_folder}"/sat-run
install -Dm 0644 -t "${tmp_folder}"/usr/libexec/sat/        sat-common
install -Dm 0644 -t "${tmp_folder}"/usr/lib/systemd/system/ sat-run@.service
install -Dm 0644 -t "${tmp_folder}"/usr/lib/systemd/user/   sat-run@.service
install -Dm 0644 -t "${tmp_folder}"/usr/share/sat/          LICENSE.md
for script in sat satq satrm
do
  install -Dm 0644 "${script}".bash_completion "${tmp_folder}"/usr/share/bash-completion/completions/"${script}"
done

# Create manuals
mkdir -p "${tmp_folder}"/usr/share/man/{man1,man8}
pod2man --section=1 --release="SAT ${CODE_VERSION}" "${tmp_folder}"/sat.pod     | gzip > "${tmp_folder}"/usr/share/man/man1/sat.1.gz
pod2man --section=1 --release="SAT ${CODE_VERSION}" "${tmp_folder}"/satq.pod    | gzip > "${tmp_folder}"/usr/share/man/man1/satq.1.gz
pod2man --section=1 --release="SAT ${CODE_VERSION}" "${tmp_folder}"/satrm.pod   | gzip > "${tmp_folder}"/usr/share/man/man1/satrm.1.gz
pod2man --section=8 --release="SAT ${CODE_VERSION}" "${tmp_folder}"/sat-run.pod | gzip > "${tmp_folder}"/usr/share/man/man8/sat-run.8.gz

# Good right
chmod -R a+rX,go-w   "${tmp_folder}"/usr

# Package size
PKG_SIZE=$(du -ks "${tmp_folder}"/usr | cut -f 1)

# Data archive
(cd "${tmp_folder}" || exit 1; tar --owner root --group root -czf data.tar.gz ./usr)

# Control file
cat <<END > "${tmp_folder}"/control
Package: ${PKG_NAME}
Version: ${CODE_VERSION}-${PKG_VERSION}
Section: utils
Tag: implemented-in::bash, interface::commandline, role::program
Priority: optional
Depends: bash, systemd, coreutils, util-linux, sed, grep
Recommends: bash-completion
Architecture: all
Installed-Size: ${PKG_SIZE}
Maintainer: Gabriel Moreau <Gabriel.Moreau@univ-grenoble-alpes.fr>
Description: Simple persistent At Scheduler
 SAT is a lightweight one-shot job scheduler for Linux systems using
 systemd. It provides an at-like user interface while using persistent
 systemd timers internally.
Homepage: https://gricad-gitlab.univ-grenoble-alpes.fr/legi/soft/trokata/sat
END

# Post install and post remove
cat <<END > "${tmp_folder}"/postinst
#!/bin/sh
set -e

/usr/bin/systemctl daemon-reload >/dev/null || true
END
cp "${tmp_folder}"/postinst "${tmp_folder}"/postrm
chmod a+rx,go-w "${tmp_folder}"/postinst "${tmp_folder}"/postrm

# Control archive
(cd "${tmp_folder}" || exit 1; tar --owner root --group root -czf control.tar.gz control postinst postrm)

# Format deb package
echo 2.0 > "${tmp_folder}"/debian-binary

# Create package (control before data)
ar -r "${PKG_NAME}_${CODE_VERSION}-${PKG_VERSION}"_all.deb "${tmp_folder}"/debian-binary "${tmp_folder}"/control.tar.gz "${tmp_folder}"/data.tar.gz
      
# Clean
rm -rf "${tmp_folder}"

# Prepare reprepro upload
echo "# Prepare reprepro upload"
for dist in buster bullseye bookworm trixie
do
  echo "( cd /srv/www/debian/ || exit 1; reprepro includedeb '${dist}' ~/${dist}/${PKG_NAME}_${CODE_VERSION}-${PKG_VERSION}_all.deb )"
done
echo "( cd /srv/www/debian/ ; reprepro dumpreferences ) | grep -i -- 'sat'"
