#!/bin/bash
#
# Script: /usr/bin/sat
# Description: submit SAT job (like at UNIX command)
# Version: @VERSION@
#
# 2026/07/24 Gabriel Moreau <Gabriel.Moreau@univ-grenoble-alpes.fr>

set -euo pipefail

export PATH=/bin:/sbin:/usr/bin:/usr/sbin
export LANG=C

# shellcheck source=/usr/libexec/sat/sat-common
source /usr/libexec/sat/sat-common

JOB_SHELL=/bin/sh

exit_usage() {
  local exit_code
  exit_code=${1:-0}

  cat <<EOF
Usage:
  sat DATE TIME               Submit a new job (run under /bin/sh)
  sat -b|--bash DATE TIME     Submit a new job (run under Bash)
  sat -z|--zsh  DATE TIME     Submit a new job (run under Zsh)
  sat -h|--help               Show this help
  sat -V|--version            Show version

Examples:
  echo "bash command" | sat 2026-08-21 12:30
  echo "bash command" | sat now +5min
  echo "bash command" | sat today 18:00
  echo "bash command" | sat tomorrow 09:30
EOF

  exit "${exit_code}"
}

trapjob_cleanup() {
  [ -n "${JOBFILE_TMP:-}" ]   && rm -f "${JOBFILE_TMP}"
  [ -n "${TIMERFILE_TMP:-}" ] && rm -f "${TIMERFILE_TMP}"
}

OPT_SHORT=bzhV
OPT_LONG=bash,zsh,help,version
if ! OPT_PARSED=$(getopt --options "${OPT_SHORT}" --longoptions "${OPT_LONG}" --name "$0" -- "$@")
then
  exit_usage 1 >&2
fi
eval set -- "${OPT_PARSED}"

# get options
while true
do
  case "$1" in
    -b|--bash)
      JOB_SHELL=/bin/bash
      shift
      ;;
    -z|--zsh)
      JOB_SHELL=/bin/zsh
      shift
      ;;
    -h|--help)
      exit_usage 0
      ;;
    -V|--version)
      echo "sat @VERSION@"
      exit 0
      ;;
    --)
      shift
      break
      ;;
    *)
      exit_usage 1 >&2
      ;;
  esac
done

if [ $# -ne 2 ]
then
  exit_usage 1 >&2
fi
DATE_ASKED="$1 $2"

# Create folder
install -dm 0700 "${SATDIR}"
install -dm 0700 "${JOBDIR}"
install -dm 0700 "${SYSTEMDDIR}"
install -dm 0700 "$(dirname "${LOCKFILE}")"

# Check job shell
if [ ! -x "${JOB_SHELL}" ]
then
  echo "sat: shell not found: ${JOB_SHELL}" >&2
  exit 1
fi
# Check date syntax and date in the future
if ! DATE_TARGET=$(date -d "${DATE_ASKED}" +%s 2>/dev/null)
then
  echo "sat: invalid date expression: ${DATE_ASKED}" >&2
  exit 1
fi
DATE_NOW=$(date +%s)
if [ "${DATE_TARGET}" -le "${DATE_NOW}" ]
then
  echo "sat: date must be in the future: ${DATE_ASKED}" >&2
  exit 1
fi

# Temporary files
JOBFILE_TMP=''
TIMERFILE_TMP=''
trap trapjob_cleanup EXIT INT TERM
JOBFILE_TMP=$(mktemp --suffix .sat.sh)
TIMERFILE_TMP=$(mktemp --suffix .sat.timer)

# Read script command from stdin
JOB_EMPTY=1
{
  echo "#!${JOB_SHELL}"
  echo "set -e"
  echo ''

  while IFS= read -r line
  do
    [ -n "${line//[[:space:]]/}" ] && JOB_EMPTY=0
    printf '%s\n' "${line}"
  done
} > "${JOBFILE_TMP}"

# Test if no empty
if [ "${JOB_EMPTY}" -eq 1 ]
then
  echo "sat: empty command" >&2
  exit 1
fi
chmod 0700 "${JOBFILE_TMP}"

# Alloc an atomic job number
exec 9>"${LOCKFILE}"
flock --exclusive 9

IDFILE="${SATDIR}"/nextid
if [ -f "${IDFILE}" ]
then
  read -r ID < "${IDFILE}"
else
  ID=1
fi
echo $((ID+1)) > "${IDFILE}"

JOBID=$(printf "%06d" "${ID}")
JOBFILE="${JOBDIR}/${JOBID}.sh"
TIMERFILE="${SYSTEMDDIR}/sat-${JOBID}.timer"

# Timer file
DATE_HMS=$(date -d "@${DATE_TARGET}" '+%Y-%m-%d %H:%M:%S')
cat > "${TIMERFILE_TMP}" <<EOF
[Unit]
Description=SAT job ${JOBID}

[Timer]
OnCalendar=${DATE_HMS}
Persistent=true
Unit=sat-run@${JOBID}.service

[Install]
WantedBy=timers.target
EOF

# Move the script job with the good ID
mv "${JOBFILE_TMP}"   "${JOBFILE}"
JOBFILE_TMP=''
mv "${TIMERFILE_TMP}" "${TIMERFILE}"
TIMERFILE_TMP=''

# Lock free
exec 9>&-

# Reload systemd
"${SYSTEMCTL[@]}" daemon-reload
"${SYSTEMCTL[@]}" enable --now "sat-${JOBID}.timer"

echo -n "scheduled job ${JOBID} at ${DATE_HMS}"
if [ "${DATE_HMS}" != "${DATE_ASKED}" ] && [ "${DATE_HMS%:00}" != "${DATE_ASKED}"  ] 
then
  echo -n " (${DATE_ASKED})"
fi
echo ''
