#!/bin/bash
#
# Script: /usr/bin/sat
# Description: submit SAT job (like at UNIX command)
#
# 2026/07/24 Gabriel Moreau <Gabriel.Moreau@univ-grenoble-alpes.fr>

set -euo pipefail

export PATH=/bin:/sbin:/usr/bin:/usr/sbin
export LANG=C

JOBDIR=/var/lib/sat/job
SYSTEMDDIR=/etc/systemd/system
JOB_SHELL=/bin/sh

exit_usage() {
  local exit_code
  exit_code=${1:-0}

  cat <<EOF
Usage: sat [--bash|-b] [--zsh|-z] DATE TIME

Examples:
  echo "my_command" | sat 2026-08-21 12:30
  echo "my_command" | sat now +5min
  echo "my_command" | sat today 18:00
  echo "my_command" | sat tomorrow 09:30
EOF

  exit "${exit_code}"
}

OPT_SHORT=bzh
OPT_LONG=bash,zsh,help
if ! OPT_PARSED=$(getopt --options "${OPT_SHORT}" --longoptions "${OPT_LONG}" --name "$0" -- "$@")
then
  exit_usage 1 >&2
fi
eval set -- "${OPT_PARSED}"

# get options
while true
do
  case "$1" in
    -b|--bash)
      JOB_SHELL=/bin/bash
      shift
      ;;
    -z|--zsh)
      JOB_SHELL=/bin/zsh
      shift
      ;;
    -h|--help)
      exit_usage 0
      ;;
    --)
      shift
      break
      ;;
    *)
      exit_usage 1 >&2
      ;;
  esac
done

if [ $# -ne 2 ]
then
  exit_usage 1 >&2
fi
DATE_ASKED="$1 $2"

mkdir -p "${JOBDIR}"

# Check job shell
if [ ! -x "${JOB_SHELL}" ]
then
  echo "sat: shell not found: ${JOB_SHELL}" >&2
  exit 1
fi
# Check date syntax and date in the future
if ! DATE_TARGET=$(date -d "${DATE_ASKED}" +%s 2>/dev/null)
then
  echo "sat: invalid date expression: ${DATE_ASKED}" >&2
  exit 1
fi
DATE_NOW=$(date +%s)
if [ "${DATE_TARGET}" -le "${DATE_NOW}" ]
then
  echo "sat: date must be in the future: ${DATE_ASKED}" >&2
  exit 1
fi

# Alloc an atomic job number
exec 9>/var/lib/sat/lock

flock 9

IDFILE=/var/lib/sat/nextid

if [ -f "${IDFILE}" ]
then
  read -r ID < "${IDFILE}"
else
  ID=1
fi

echo $((ID+1)) > "${IDFILE}"

JOBID=$(printf "%06d" "${ID}")

JOBFILE="${JOBDIR}/${JOBID}.sh"
TIMERFILE="${SYSTEMDDIR}/sat-${JOBID}.timer"

# Read script from stdin
{
  echo "#!${JOB_SHELL}"
  echo "set -e"
  echo ''
  cat
} > "${JOBFILE}"
chmod 0700 "${JOBFILE}"

DATE_HMS=$(date -d "@${DATE_TARGET}" '+%Y-%m-%d %H:%M:%S')
cat > "${TIMERFILE}" <<EOF
[Unit]
Description=SAT job ${JOBID}

[Timer]
OnCalendar=${DATE_HMS}
Persistent=true
Unit=sat-run@${JOBID}.service

[Install]
WantedBy=timers.target
EOF

systemctl daemon-reload
systemctl enable --now "sat-${JOBID}.timer"

echo -n "scheduled job ${JOBID} at ${DATE_HMS}"
if [ "${DATE_HMS}" != "${DATE_ASKED}" ] && [ "${DATE_HMS%:00}" != "${DATE_ASKED}"  ] 
then
  echo -n " (${DATE_ASKED})"
fi
echo ''
