=head1 NAME

satq - list scheduled SAT jobs

=head1 SYNOPSIS

 satq

=head1 DESCRIPTION

SAT was designed as a lightweight system administration tool providing an B<at>-like interface with systemd persistence.

B<satq> displays the list of jobs scheduled by B<sat>.

For each job, it shows:

=over 4

=item * the job identifier;

=item * the next scheduled execution time;

=item * the current state;

=item * the command to be executed.

=back

Jobs are managed by systemd timers and are persistent across system reboots.


=head1 EXAMPLES

List scheduled jobs:

 satq


Example output:

 ID       NEXT RUN                   STATE     COMMAND
 000042   2026-08-31 23:59           waiting   usermgmt to-staff --employer DoD --job Programmer toto
 000043   2026-09-01 08:00           failed    backup --full


=head1 EXIT STATUS

B<satq> returns:

=over 4

=item 0 Successful completion.

=item 1 An error occurred.

=back


=head1 FILES

 (root) /var/lib/sat/job/
 (user) ~/.local/state/sat/job/

 (root) /etc/systemd/system/sat-*.timer
 (user) ~/.config/systemd/user/sat-*.timer


=head1 SEE ALSO

L<sat(1)|https://legi.gricad-pages.univ-grenoble-alpes.fr/soft/trokata/sat/sat.html>,
L<satq(1)|https://legi.gricad-pages.univ-grenoble-alpes.fr/soft/trokata/sat/satq.html>,
L<satrm(1)|https://legi.gricad-pages.univ-grenoble-alpes.fr/soft/trokata/sat/satrm.html>,
L<sat-run(8)|https://legi.gricad-pages.univ-grenoble-alpes.fr/soft/trokata/sat/sat-run.html>,
L<systemd.timer(5)>,
L<systemd.service(5)>,
L<journalctl(1)>,
L<loginctl(1)>

Project resources:

=over

=item * L<Web site (Gitlab)|https://gricad-gitlab.univ-grenoble-alpes.fr/legi/soft/trokata/sat>

=item * L<Download package (Debian)|https://legi.gricad-pages.univ-grenoble-alpes.fr/soft/trokata/sat/download/>

=back

Note: The master Git repository in on the L<GRICAD Gitlab|https://gricad-gitlab.univ-grenoble-alpes.fr/legi/soft/trokata/sat>.
Other Git repository are mirror or fork.


=head1 VERSION

SAT version @VERSION@


=head1 AUTHORS

Written by Gabriel Moreau <Gabriel.Moreau(A)univ-grenoble-alpes.fr> - Grenoble - France


=head1 LICENSE AND COPYRIGHT

License GNU GPL version 2 or later and Perl equivalent

 Copyright (C) 2026, LEGI UMR 5519 / CNRS UGA G-INP, Grenoble, France
